### ISSUE TITLE
WidgetValues could be array

### ISSUE THREAD

**Issue by m-schreiber** [Magenerds/WysiwygWidget#1]
Magento-Version: 2.3

Issue:
After adding a "Catalog Product List"-Widget editing is not possible because of array to string exception.

Solution:
Do not cast to string at this line.
https://github.com/Magenerds/WysiwygWidget/blob/748f78b90d4add56d61b507f4979a2c95d7942ac/Wysiwyg/Encoder.php#L83

**Comment by sippsolutions** [comment]
@m-schreiber this should be fixed in WysiwygWidget 1.0.5. Feel free to update. Thanks for reporting! :)
